Lab4/Models/Community.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lab4.Models
{
    public class Community
    {
        [Required]
        [Display(Name = "Registration Number")]
        public string ID
        {
            get;
            set;
        }

        [Required]
        [StringLength(50,MinimumLength = 3,ErrorMessage = "Enter string within 3 -50 characters")]
        public string Title
        {
            get;
            set;
        }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Budget
        {
            get;
            set;
        }

        public IEnumerable<CommunityMembership> CommunityMemberships
        {
            get;
            set;
        }
    }
}

Lab4/Models/ViewModels/CommunityViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Models.ViewModel
{
    public class CommunityViewModel
    {
        public IEnumerable<Student> Students { get; set; }
        public IEnumerable<Community> Communities { get; set; }
        public IEnumerable<CommunityMembership> CommunityMemberships { get; set; }

    }
}

Lab4/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Azure;
using Azure.Storage.Blobs;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab5.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly SchoolCommunityContext _context;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly string containerName = "answerimages";

        public AdvertisementController(SchoolCommunityContext context, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _blobServiceClient = blobServiceClient;
        }


        public async Task<IActionResult> Index(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = new AdsViewModel()
            {
                Community = await _context.Communities.FindAsync(id),
                Advertisements = await _context.Advertisements
                .Where(x => x.CommunityID == id).OrderBy(x=>x.Id)
                .AsNoTracking().ToListAsync()               
            };

            return View(data);
        }

        [HttpGet]
        public IActionResult Upload(string id)
        {
            ViewData["communityID"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file, string ID)
        {
            if (file == null)
            {
                return RedirectToAction("Index", new { id = ID });
            }

            BlobContainerClient containerClient;
            // Create the container and return a container client object
            try
            {
                containerClient = await _blobServiceClient.CreateBlobContainerAsync(containerName);
                containerClient.SetAccessPolicy(Azure.Storage.Blobs.Models.PublicAccessType.BlobContainer);
            }
            catch (RequestFailedException)
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }


            try
            {
                // create the blob to hold the data
                var blockBlob = containerClient.GetBlobClient(file.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    await blockBlob.DeleteAsync();
                }

                using (var memoryStream = new MemoryStream())
                {
                    // copy the file data into memory
                    await file.CopyToAsync(memoryStream);

                    // navigate back to the beginning of the memory stream
                    memoryStream.Position = 0;

                    // send the file to the cloud
                    await blockBlob.UploadAsync(memoryStream);
                    memoryStream.Close();
                }

                // add the photo to the database if it uploaded successfully
                var image = new Advertisement();
                image.Url = blockBlob.Uri.AbsoluteUri;
                image.FileName = file.FileName;
                image.CommunityID = ID;

                _context.Advertisements.Add(image);
                _context.SaveChanges();
            }
            catch (RequestFailedException)
            {
                View("Error");
            }

            return RedirectToAction("Index", new { id = ID });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Advertisements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, string communityID)
        {
            var image = await _context.Advertisements.FindAsync(id);


            BlobContainerClient containerClient;
            // Get the container and return a container client object
            try
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            try
            {
                int count = _context.Advertisements.Where(x => x.Url == image.Url).Count();

                 _context.Advertisements.Remove(image);
                await _context.SaveChangesAsync();

                // Get the blob that holds the data
                var blockBlob = containerClient.GetBlobClient(image.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    if(count==1)
                    await blockBlob.DeleteAsync();
                }

               

            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            return RedirectToAction("Index", new { id=communityID});
        }

    }
}

Lab4/Controllers/CommunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModel;
using Lab4.Models.ViewModels;
using System.Security.Cryptography.X509Certificates;

namespace Lab4.Controllers
{
    public class CommunityController : Controller
    {
        private readonly SchoolCommunityContext _context;

        public CommunityController(SchoolCommunityContext context)
        {
            _context = context;
        }

        // GET: Community
        public async Task<IActionResult> Index(string ID)
        {
            //return View(await _context.Communities.ToListAsync());
            var viewModel = new CommunityViewModel();
            viewModel.Communities = await _context.Communities
                .Include(c => c.CommunityMemberships)
                .ThenInclude(s=>s.Student)
                .OrderBy(c=>c.ID)
                .AsNoTracking()
                .ToListAsync();

            ViewData["CommunityID"] = "None";

            if (ID != null)
            {
                ViewData["CommunityID"] = ID;
                viewModel.CommunityMemberships = viewModel.Communities.Where(x => x.ID == ID).Single().
                    CommunityMemberships.Where(x => x.CommunityID == ID);

            }
            //else
            //{
            //    ViewData["CommunityID"] = ID;
            //    viewModel.CommunityMemberships = viewModel.Communities.Where(x => x.ID == "A1").Single().
            //       CommunityMemberships;
            //}

            return View(viewModel);
        }

        // GET: Community/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities
                .FirstOrDefaultAsync(m => m.ID == id);
            if (community == null)
            {
                return NotFound();
            }

            return View(community);
        }

        // GET: Community/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Community/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Budget")] Community community)
        {
            if (ModelState.IsValid)
            {
                _context.Add(community);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities.FindAsync(id);
            if (community == null)
            {
                return NotFound();
            }
            return View(community);
        }

        // POST: Community/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Title,Budget")] Community community)
        {
            if (id != community.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(community);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommunityExists(community.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var community = await _context.Communities
                .FirstOrDefaultAsync(m => m.ID == id);
            if (community == null)
            {
                return NotFound();
            }

            var data = new AdsViewModel()
            {
                Community = community,
                Advertisements = await _context.Advertisements
                .Where(x => x.CommunityID == id).AsNoTracking().ToListAsync()
            };

            return View(data);
        }

        // POST: Community/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var community = await _context.Communities.FindAsync(id);
            _context.Communities.Remove(community);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommunityExists(string id)
        {
            return _context.Communities.Any(e => e.ID == id);
        }
    }
}

Lab4/Views/Community/Create.cshtml
@model Lab4.Models.Community

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Community</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab4/Views/Community/Delete.cshtml
@model Lab4.Models.ViewModels.AdsViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Community</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Community.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Community.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Community.Budget)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Community.Budget)
        </dd>
    </dl>

    @if (Model.Advertisements.Count() == 0)
    {
        <form asp-action="Delete">
            <input type="hidden" asp-for="Community.ID" />
            <input type="submit" value="Delete" class="btn btn-danger" /> <br />
            <a asp-action="Index">Back to List</a>
        </form>
    }
    else
    {
        <h4>You cannot delete a community untill all associated advertisements are deleted</h4>
        <a asp-action="Index">Back to List</a>
    }

</div>

Lab4/Views/Community/Details.cshtml
@model Lab4.Models.Community

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Community</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lab4/Views/Community/Edit.cshtml
@model Lab4.Models.Community

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Community</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab4/Views/Community/Index.cshtml
@*@model IEnumerable<Lab4.Models.Community>*@

@model Lab4.Models.ViewModel.CommunityViewModel

@{
    ViewData["Title"] = "Communities";
}

<h1>Communities</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Communities.ElementAt(0).Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.Communities.ElementAt(0).Budget)
            </th>
            <th>
                Operating
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Communities)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Budget)
                </td>
                <td>
                    <a asp-action="Index" asp-route-id="@item.ID">Select</a> |
                    <a asp-controller="Advertisement" asp-action="Index" asp-route-id="@item.ID">Ads</a> |
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>

@if (Model.CommunityMemberships != null)
{
    <h2>Members of the community</h2>
    @if (Model.CommunityMemberships.Count()>0)
    {
    <table>
        <tr>
            <td>
                <font style="font-weight: bold" color="red" face="Verdana">
                    Name:
                </font>
               
            </td>
        </tr>
        <tr>
            <td>
                <ol>
                    @foreach (var item1 in Model.CommunityMemberships)
                    {
                        <li>@Html.DisplayFor(modelItem => item1.Student.FullName)</li>
                    }
                </ol>
            </td>
        </tr>
    </table>
    }
    else
    {
        <h4>No membership exists</h4>
    }
}