Lab4/Models/Advertisement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Models
{
    public class Advertisement
    {
        public int Id
        {
            set;
            get;
        }

        public string CommunityID
        {
            set;
            get;
        }

        [Required]
        [DisplayName("File Name")]
        public string FileName
        {
            set;
            get;
        }

        [Required]
        [Url]
        public string Url
        {
            set;
            get;
        }


    }
}

Lab4/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Azure;
using Azure.Storage.Blobs;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab5.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly SchoolCommunityContext _context;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly string containerName = "answerimages";

        public AdvertisementController(SchoolCommunityContext context, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _blobServiceClient = blobServiceClient;
        }


        public async Task<IActionResult> Index(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = new AdsViewModel()
            {
                Community = await _context.Communities.FindAsync(id),
                Advertisements = await _context.Advertisements
                .Where(x => x.CommunityID == id).OrderBy(x=>x.Id)
                .AsNoTracking().ToListAsync()               
            };

            return View(data);
        }

        [HttpGet]
        public IActionResult Upload(string id)
        {
            ViewData["communityID"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file, string ID)
        {
            if (file == null)
            {
                return RedirectToAction("Index", new { id = ID });
            }

            BlobContainerClient containerClient;
            // Create the container and return a container client object
            try
            {
                containerClient = await _blobServiceClient.CreateBlobContainerAsync(containerName);
                containerClient.SetAccessPolicy(Azure.Storage.Blobs.Models.PublicAccessType.BlobContainer);
            }
            catch (RequestFailedException)
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }


            try
            {
                // create the blob to hold the data
                var blockBlob = containerClient.GetBlobClient(file.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    await blockBlob.DeleteAsync();
                }

                using (var memoryStream = new MemoryStream())
                {
                    // copy the file data into memory
                    await file.CopyToAsync(memoryStream);

                    // navigate back to the beginning of the memory stream
                    memoryStream.Position = 0;

                    // send the file to the cloud
                    await blockBlob.UploadAsync(memoryStream);
                    memoryStream.Close();
                }

                // add the photo to the database if it uploaded successfully
                var image = new Advertisement();
                image.Url = blockBlob.Uri.AbsoluteUri;
                image.FileName = file.FileName;
                image.CommunityID = ID;

                _context.Advertisements.Add(image);
                _context.SaveChanges();
            }
            catch (RequestFailedException)
            {
                View("Error");
            }

            return RedirectToAction("Index", new { id = ID });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Advertisements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, string communityID)
        {
            var image = await _context.Advertisements.FindAsync(id);


            BlobContainerClient containerClient;
            // Get the container and return a container client object
            try
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            try
            {
                int count = _context.Advertisements.Where(x => x.Url == image.Url).Count();

                 _context.Advertisements.Remove(image);
                await _context.SaveChangesAsync();

                // Get the blob that holds the data
                var blockBlob = containerClient.GetBlobClient(image.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    if(count==1)
                    await blockBlob.DeleteAsync();
                }

               

            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            return RedirectToAction("Index", new { id=communityID});
        }

    }
}

Lab4/Controllers/CommunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModel;
using Lab4.Models.ViewModels;
using System.Security.Cryptography.X509Certificates;

namespace Lab4.Controllers
{
    public class CommunityController : Controller
    {
        private readonly SchoolCommunityContext _context;

        public CommunityController(SchoolCommunityContext context)
        {
            _context = context;
        }

        // GET: Community
        public async Task<IActionResult> Index(string ID)
        {
            //return View(await _context.Communities.ToListAsync());
            var viewModel = new CommunityViewModel();
            viewModel.Communities = await _context.Communities
                .Include(c => c.CommunityMemberships)
                .ThenInclude(s=>s.Student)
                .OrderBy(c=>c.ID)
                .AsNoTracking()
                .ToListAsync();

            ViewData["CommunityID"] = "None";

            if (ID != null)
            {
                ViewData["CommunityID"] = ID;
                viewModel.CommunityMemberships = viewModel.Communities.Where(x => x.ID == ID).Single().
                    CommunityMemberships.Where(x => x.CommunityID == ID);

            }
            //else
            //{
            //    ViewData["CommunityID"] = ID;
            //    viewModel.CommunityMemberships = viewModel.Communities.Where(x => x.ID == "A1").Single().
            //       CommunityMemberships;
            //}

            return View(viewModel);
        }

        // GET: Community/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities
                .FirstOrDefaultAsync(m => m.ID == id);
            if (community == null)
            {
                return NotFound();
            }

            return View(community);
        }

        // GET: Community/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Community/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Budget")] Community community)
        {
            if (ModelState.IsValid)
            {
                _context.Add(community);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities.FindAsync(id);
            if (community == null)
            {
                return NotFound();
            }
            return View(community);
        }

        // POST: Community/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Title,Budget")] Community community)
        {
            if (id != community.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(community);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommunityExists(community.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var community = await _context.Communities
                .FirstOrDefaultAsync(m => m.ID == id);
            if (community == null)
            {
                return NotFound();
            }

            var data = new AdsViewModel()
            {
                Community = community,
                Advertisements = await _context.Advertisements
                .Where(x => x.CommunityID == id).AsNoTracking().ToListAsync()
            };

            return View(data);
        }

        // POST: Community/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var community = await _context.Communities.FindAsync(id);
            _context.Communities.Remove(community);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommunityExists(string id)
        {
            return _context.Communities.Any(e => e.ID == id);
        }
    }
}

Lab4/Views/Advertisement/Delete.cshtml
@model Lab4.Models.Advertisement;

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class="col-sm-2">
           Image
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.Url" style="max-width: 400px;" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="CommunityID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-id="@Model.CommunityID" >Back to List</a>
    </form>
</div>

Lab4/Views/Advertisement/Index.cshtml
@model Lab4.Models.ViewModels.AdsViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Show ads for community @Model.Community.Title</h1>

<p>
    <a asp-action="Upload" asp-route-id="@Model.Community.ID">Upload New</a> <br />
    <a asp-controller="Community" asp-action="Index" >Back to List</a>
</p>
@if (Model.Advertisements.Count()==0)
{
    <p>There are no files to display.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Advertisements.ElementAt(0).FileName);
                </th>
                <th>
                    Image
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Advertisements)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileName)
                    </td>
                    <td>
                        <img src="@item.Url" style="max-width: 400px;" />
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Lab4/Views/Advertisement/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}

<h1>Upload</h1>

<h4>Upload an image</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Upload" enctype="multipart/form-data">
            <div class="form-group">
                <div class="btn btn-sm float-left">
                    <input name="file" type="file">
                    <input type="hidden" asp-for="@ViewData["communityID"]" />
                </div>
            </div>

            <div class="form-group">
                <button name="upload" class="btn btn-primary">Upload Now</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@ViewData["communityID"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}